a = input("Enter a first list of numbers, separated by spaces: ")
b = input("Enter a second of numbers, separated by spaces: ")
input_listA =(a).split()   
input_listB =(b).split()   
numbersA = set([int(i) for i in input_listA])
numbersB = set([int(i) for i in input_listB])
duplicate_numbers = list(numbersA.intersection(numbersB))
duplicate_numbers.sort()
print(duplicate_numbers)